apiVersion: skaffold/v1alpha5
kind: Config
#build:
#  artifacts:
#  - imageName: buildbot-kubernetes
#    workspace: images/buildbot-kubernetes
deploy:
  helm:
    releases:
    - name: bb-kube-dev
      chartPath: helm/buildbot
      namespace: bb-kube-dev
#      values:
#        image: buildbot-kubernetes
      overrides:
        postgresql:
          postgresPassword: skaffold
        secret:
          values:
            foo: bar
        config:
          factories:
          - |-
            factory = util.BuildFactory()
            # check out the source
            factory.addStep(steps.Git(repourl='git://github.com/buildbot/hello-world.git', mode='incremental'))
            # run the tests (note that this will require that 'trial' is installed)
            factory.addStep(steps.ShellCommand(command=["trial", "hello"], env={"PYTHONPATH": "."}))
            factory.addStep(steps.ShellCommand(command=["touch", util.Secret("foo")]))
