{{ if not .Values.secret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    app.kubernetes.io/name: {{ include "buildbot.name" . }}
    helm.sh/chart: {{ include "buildbot.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
{{ range $key, $value := .Values.secret.values }}
  {{ $key }}: {{ $value|b64enc | quote }}
{{ end }}
{{- end }}
