apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "buildbot.name" . }}
    chart: {{ template "buildbot.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    compotent: {{ template "buildbot.name" . }}-crossbar
  name: {{ template "buildbot.fullname" . }}-crossbar
spec:
  selector:
    app: {{ template "buildbot.name" . }}
    chart: {{ template "buildbot.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    compotent: {{ template "buildbot.name" . }}-crossbar
  ports:
  - name: crossbar
    port: 8080
    targetPort: 8080
    protocol: TCP
