---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ include "buildbot.fullname" . }}-worker
  labels:
    app.kubernetes.io/name: {{ include "buildbot.name" . }}
    helm.sh/chart: {{ include "buildbot.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: buildbot-worker
spec:
  serviceName: {{ include "buildbot.fullname" . }}-worker
  replicas: {{ .Values.worker.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "buildbot.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: buildbot-worker
    spec:
      containers:
      - name: worker
        image: {{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}
        imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
        env:
        - name: BUILDMASTER
          value: '{{ include "buildbot.fullname" . }}-master-pb'
        - name: BUILDMASTER_PORT
          value: '9989'
        - name: WORKERNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: WORKERPASS
          valueFrom:
            secretKeyRef:
{{- if .Values.worker.password.secret_name}}
              name: {{ .Values.worker.password.secret_name }}
{{- else }}
              name: {{ include "buildbot.fullname" . }}-worker-secret
{{- end }}
              key: {{ .Values.worker.password.key }}
