{{- if and .Values.worker.enabled (not .Values.worker.password.secret_name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "buildbot.fullname" . }}-worker-secret
  labels:
    app: {{ template "buildbot.name" . }}
    chart: {{ template "buildbot.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- if .Values.worker.password.value }}
  {{ .Values.worker.password.key }}: {{ .Values.worker.password.value | b64enc | quote }}
{{- else }}
  {{ .Values.worker.password.key }}: {{ randAlphaNum 10 |b64enc | quote }}
{{- end }}
{{- end }}
