{{- if and .Values.worker.enabled (not .Values.worker.password.secret_name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "buildbot.fullname" . }}-worker-secret
  labels:
    app.kubernetes.io/name: {{ include "buildbot.name" . }}
    helm.sh/chart: {{ include "buildbot.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
{{- if .Values.worker.password.value }}
  {{ .Values.worker.password.key }}: {{ .Values.worker.password.value | b64enc | quote }}
{{- else }}
  {{ .Values.worker.password.key }}: {{ randAlphaNum 10 |b64enc | quote }}
{{- end }}
{{- end }}
