version: 2
jobs:
  test:
    docker:
    - image: gcr.io/k8s-skaffold/skaffold:v0.19.0
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: 'setup a kubernetes'
        command: |
          set -x
          ./hack/dependencies.sh
          KUBE_VERSION=v1.11 ./hack/kubernetes-dind.sh
          helm init
          for _ in $(seq 1 30); do
             helm version && break
             sleep 1
          done
    - run:
        name: 'run skaffold'
        command: |
          ./portforward.sh 32768
          make test

  docs:
    docker:
    - image: gcr.io/k8s-skaffold/skaffold:v0.19.0
    steps:
    - checkout
    - run:
        name: 'Install missing package'
        command: |
          ./hack/dependencies.sh
    - run:
        name: 'build doc'
        command: |
          make docs
    - persist_to_workspace:
        root: build
        paths:
        - docs


  release:
    docker:
    - image: gcr.io/k8s-skaffold/skaffold:v0.19.0
    steps:
    - checkout
    - run:
        name: 'Install missing package'
        command: |
          ./hack/dependencies.sh
          /usr/lib/go-1.9/bin/go get -v github.com/github/hub
        environment:
          GOPATH: "/root"
    - attach_workspace:
        at: build
    - add_ssh_keys:
        fingerprints:
          - "b2:b2:1a:64:60:47:fc:e4:f1:27:40:59:d7:1b:d7:26"
    - run:
        name: 'Make release'
        command: |
          export PATH=$PATH:$GOPATH/bin
          git config --global user.email "ci@buildbot-kubernetes.github.io"
          git config --global user.name "ci buildbot-kubernetes"

          helm init --client-only
          make release-docs
          make release
          cd build/buildbot-kubernetes.github.io
          git push
        environment:
          GOPATH: "/root"
          GIT_SSH_COMMAND: "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"

workflows:
  version: 2
  test_and_release:
    jobs:
    - test
    - docs
    - release:
        requires:
        - test
        - docs
        filters:
          branches:
            only: master
