version: 2
jobs:
  build:
    docker:
      - image: gcr.io/k8s-skaffold/skaffold:v0.16.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: 'setup a kubernetes'
          command: |
            set -x
            ./.circleci/dependencies.sh
            KUBE_VERSION=v1.11 ./.circleci/kubernetes-dind.sh
            helm init
            for _ in $(seq 1 30); do
               helm version && break
               sleep 1
            done
      - run:
          name: 'run skaffold'
          command: |
            ./portforward.sh 32768
            skaffold run
